<a href="https://colab.research.google.com/github/Shalu31/comment_toxicity/blob/main/commenttoxicity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
train = pd.read_csv('/content/drive/MyDrive/train.csv')

In [5]:
test = pd.read_csv('/content/drive/MyDrive/test.csv')

In [6]:
train

id                                       comment_text  \
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...   
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...   
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...   
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...   
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...   
...                  ...                                                ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
0           0             0        0       0       0              0  
1           0             0        0       0       0              0  
2           0             0        0       0       0              0  
3           0             0        0       0       0              0  
4           0             0        0       0       0              0  
...       ...           ...      ...     ...     ...            ...  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0  

[159571 rows x 8 columns]

In [7]:
train = train.drop([153163, 159570])

In [9]:
train = train.reset_index(drop=True)

print(train.shape)

(159569, 8)


In [10]:
train.shape

(159569, 8)

In [11]:
import re
import string
def clean_text(text):
  text = text.lower()
  text = re.sub(r'httpS+', '',text)
  text = re.sub(r'<.*?>', '',text)
  text = re.sub(r'\[.*?]+', '',text)
  text = re.sub(r'[%s]' % re.escape(string.punctuation), '',text)
  text = re.sub(r'\w*\d\w*', '',text)
  text = re.sub(r'\n', '',text)
  text = text.strip()

  return text

In [12]:
train['cleaned_comment'] = train['comment_text'].apply(clean_text)
print(train[['comment_text', 'cleaned_comment']].head())

                                        comment_text  \
0  Explanation\nWhy the edits made under my usern...   
1  D'aww! He matches this background colour I'm s...   
2  Hey man, I'm really not trying to edit war. It...   
3  "\nMore\nI can't make any real suggestions on ...   
4  You, sir, are my hero. Any chance you remember...   

                                     cleaned_comment  
0  explanationwhy the edits made under my usernam...  
1  daww he matches this background colour im seem...  
2  hey man im really not trying to edit war its j...  
3  morei cant make any real suggestions on improv...  
4  you sir are my hero any chance you remember wh...  


In [13]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [14]:
def tokenize_and_remove_stopwords(text):
  tokens = word_tokenize(text)
  tokens = [word for word in tokens if word not in stop_words]
  return tokens

In [15]:
train['tokens'] = train['cleaned_comment'].apply(tokenize_and_remove_stopwords )
print(train[['cleaned_comment','tokens']].head())

                                     cleaned_comment  \
0  explanationwhy the edits made under my usernam...   
1  daww he matches this background colour im seem...   
2  hey man im really not trying to edit war its j...   
3  morei cant make any real suggestions on improv...   
4  you sir are my hero any chance you remember wh...   

                                              tokens  
0  [explanationwhy, edits, made, username, hardco...  
1  [daww, matches, background, colour, im, seemin...  
2  [hey, man, im, really, trying, edit, war, guy,...  
3  [morei, cant, make, real, suggestions, improve...  
4         [sir, hero, chance, remember, page, thats]  


In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 5000, stop_words= 'english')
X = tfidf.fit_transform(train['cleaned_comment'])

In [17]:
print(tfidf.get_feature_names_out())

['abc' 'abide' 'ability' ... 'zero' 'zionist' 'zone']


In [18]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
test.head()

id                                       comment_text
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3  00017563c3f7919a  :If you have a look back at the source, the in...
4  00017695ad8997eb          I don't anonymously edit articles at all.

In [20]:
test['cleaned'] = test['comment_text'].apply(clean_text)

In [21]:
test['cleaned_comment'] = test['comment_text'].apply(clean_text)
print(test[['comment_text', 'cleaned_comment']].head())

                                        comment_text  \
0  Yo bitch Ja Rule is more succesful then you'll...   
1  == From RfC == \n\n The title is fine as it is...   
2  " \n\n == Sources == \n\n * Zawe Ashton on Lap...   
3  :If you have a look back at the source, the in...   
4          I don't anonymously edit articles at all.   

                                     cleaned_comment  
0  yo bitch ja rule is more succesful then youll ...  
1          from rfc   the title is fine as it is imo  
2                sources    zawe ashton on lapland —  
3  if you have a look back at the source the info...  
4            i dont anonymously edit articles at all  


In [22]:
test['tokens'] = test['cleaned_comment'].apply(tokenize_and_remove_stopwords )
print(test[['cleaned_comment','tokens']].head())

                                     cleaned_comment  \
0  yo bitch ja rule is more succesful then youll ...   
1          from rfc   the title is fine as it is imo   
2                sources    zawe ashton on lapland —   
3  if you have a look back at the source the info...   
4            i dont anonymously edit articles at all   

                                              tokens  
0  [yo, bitch, ja, rule, succesful, youll, ever, ...  
1                            [rfc, title, fine, imo]  
2                [sources, zawe, ashton, lapland, —]  
3  [look, back, source, information, updated, cor...  
4                [dont, anonymously, edit, articles]  


In [27]:
test.shape

(153164, 5)

In [28]:
Y = tfidf.fit_transform(test['cleaned_comment'])

In [29]:
print(tfidf.get_feature_names_out())

['aa' 'ability' 'able' ... 'கள' 'つameno' 'ㅂㄱㅇ']


In [30]:
y_train = train['toxic'].values

In [33]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(Y,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [153164, 159569]

In [35]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X,y_train)

LogisticRegression()

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 5000, stop_words= 'english')
X = tfidf.fit_transform(train['cleaned_comment'])

In [36]:
train['cleaned_comment'].tail(10)

159559    editing of article without consensus  removal ...
159560    no he did not read it again i would have thoug...
159561    auto guides and the motoring press are not goo...
159562    please identify what part of blp applies becau...
159563    catalan independentism is the social movement ...
159564    the numbers in parentheses are the additional ...
159565    and for the second time of asking when your vi...
159566    you should be ashamed of yourself that is a ho...
159567    spitzer umm theres no actual article for prost...
159568    and it looks like it was actually you who put ...
Name: cleaned_comment, dtype: object

In [37]:
train['cleaned_comment'].sample(5)

115244                          hope that explains things o
5113      every edit that user made was in furtherance o...
87288     congratulations on your new ga i passed astaro...
76291     utcarticles about colleges are not the right p...
32973                  so where could i propose this change
Name: cleaned_comment, dtype: object

In [38]:
print(train.loc[153163, ['comment_text', 'cleaned_comment']])
print(train.loc[159570, ['comment_text', 'cleaned_comment']])

comment_text       Sounds good to me. I've removed the deletion r...
cleaned_comment    sounds good to me ive removed the deletion req...
Name: 153163, dtype: object


KeyError: 159570

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y_train, test_size=0.2, random_state=42)

In [41]:
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [43]:
print("Validation Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Validation Accuracy: 0.9559440997681269
              precision    recall  f1-score   support

           0       0.96      0.99      0.98     28850
           1       0.91      0.60      0.72      3064

    accuracy                           0.96     31914
   macro avg       0.93      0.80      0.85     31914
weighted avg       0.95      0.96      0.95     31914



In [45]:
X_test_original = tfidf.transform(test['cleaned_comment'])
test_preds = model.predict(X_test_original)
test['predicted_toxic'] = test_preds

# Save predictions
test[['comment_text', 'predicted_toxic']].to_csv("test_predictions.csv", index=False)
print(test.head())

                 id                                       comment_text  \
0  00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...   
1  0000247867823ef7  == From RfC == \n\n The title is fine as it is...   
2  00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...   
3  00017563c3f7919a  :If you have a look back at the source, the in...   
4  00017695ad8997eb          I don't anonymously edit articles at all.   

                                             cleaned  \
0  yo bitch ja rule is more succesful then youll ...   
1          from rfc   the title is fine as it is imo   
2                sources    zawe ashton on lapland —   
3  if you have a look back at the source the info...   
4            i dont anonymously edit articles at all   

                                     cleaned_comment  \
0  yo bitch ja rule is more succesful then youll ...   
1          from rfc   the title is fine as it is imo   
2                sources    zawe ashton on lapland